name: arcaea_helper_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0+6

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  url_launcher: ^6.3.0
  image: ^4.1.7
  http: ^1.2.0
  intl: ^0.19.0
  gal: ^2.3.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "../icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "../icon.png"

flutter:
  uses-material-design: true
  assets:
    - web/js/arcaea-calculator.js
    - web/js/arcaea-data-loader.js
    - web/js/flutter-content.js
    - web/css/arcaea-styles.css
    - assets/data/ChartConstant.json
    - assets/data/Songlist.json
    - assets/data/chart-data.json
  
  fonts:
    - family: Fira Sans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 700
